#!/usr/bin/env python3
"""Generate docs/plugins.js — the doc site's PLUGINS data — from each plugin's
plugin.yml (the `suite:` block). Plugin order follows marketplace.json. Every
plugin must ship a plugin.yml with a suite: block; a missing one fails the build
(no fallback). docs/plugins.js is ephemeral — regenerated each deploy, not committed.

Three fields are merged in beyond the suite: block, all kept fresh by the
on-release rebuild:
  - version    — authoritative in plugin.yml; the catalog card shows it as a badge.
  - components — the current named skills/rules/hooks/commands/agents, derived by
                 replaying suite/artifacts.csv (never declared, per the schema's
                 "Not in plugin.yml" rule); the card's expander lists them.
  - reference  — whether the plugin's doc site publishes a command reference at
                 /cli, which a top-level cli: block is what decides: shipyard
                 records the CLI's grammar from that block and renders the page.
                 `suite: cli:` on its own only says a CLI ships, so the card links
                 its mark to the reference where there is one and leaves it a
                 plain mark where there isn't.
"""
import csv
import json
import pathlib
import sys

from _common import CATS, ROOT, load_plugin, plugin_names, replay

ARTIFACTS = ROOT / "suite" / "artifacts.csv"
TARGET = ROOT / "docs" / "plugins.js"


def component_sets() -> dict[str, dict[str, list[str]]]:
    """Each plugin's current named artifacts, by category, from the replayed log.
    Empty categories are dropped so the card renders only what a plugin has."""
    rows = list(csv.DictReader(ARTIFACTS.open(newline="")))
    return {
        name: {c: sorted(members[c]) for c in CATS if members[c]}
        for name, members in replay(rows).items()
    }


def main() -> int:
    components = component_sets()
    plugins = {}
    for name in plugin_names():  # marketplace.json order
        spec = load_plugin(name)
        if spec is None or "suite" not in spec:
            print(f"ERROR: {name}/plugin.yml is missing or has no suite: block", file=sys.stderr)
            return 1
        entry = spec["suite"]
        if "version" in spec:
            entry["version"] = str(spec["version"])
        if "cli" in spec:
            entry["reference"] = True
        if name in components:
            entry["components"] = components[name]
        plugins[name] = entry

    body = json.dumps(plugins, indent=2, ensure_ascii=False)
    TARGET.write_text(
        "// Generated by suite/build-plugins-data.py — do not edit by hand.\n"
        "// Per-plugin content comes from each plugin's plugin.yml (suite: block).\n"
        f"const PLUGINS = {body};\n"
    )
    print(f"wrote {TARGET.relative_to(ROOT)} — {len(plugins)} plugins from plugin.yml")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
