#!/usr/bin/env python3
"""Generate docs/plugins.js — the doc site's PLUGINS data — from each plugin's
plugin.yml (the `suite:` block). Plugin order follows marketplace.json. Every
plugin must ship a plugin.yml with a suite: block; a missing one fails the build
(no fallback). docs/plugins.js is ephemeral — regenerated each deploy, not committed.

Fields merged in beyond the suite: block, all kept fresh by the on-release rebuild:
  - version    — authoritative in plugin.yml; the catalog card shows it as a badge.
  - components — the current named skills/rules/hooks/commands/agents, derived by
                 replaying suite/artifacts.csv (never declared, per the schema's
                 "Not in plugin.yml" rule); the card's expander lists them.
  - tier / why — the adoption tier and its rationale, from suite/tiers.yml. A tier
                 is a judgment about a plugin relative to its siblings, so it's
                 declared suite-side rather than in the plugin's own descriptor.

The tier vocabulary itself (key, label, blurb, order) is emitted alongside PLUGINS
as TIERS, because the catalog renders synchronously from this file — the tier data
has to be here rather than in a fetched .json.
"""
import csv
import json
import pathlib
import sys

import yaml

from _common import CATS, ROOT, load_plugin, plugin_names, replay

ARTIFACTS = ROOT / "suite" / "artifacts.csv"
TIERS = ROOT / "suite" / "tiers.yml"
TARGET = ROOT / "docs" / "plugins.js"


def component_sets() -> dict[str, dict[str, list[str]]]:
    """Each plugin's current named artifacts, by category, from the replayed log.
    Empty categories are dropped so the card renders only what a plugin has."""
    rows = list(csv.DictReader(ARTIFACTS.open(newline="")))
    return {
        name: {c: sorted(members[c]) for c in CATS if members[c]}
        for name, members in replay(rows).items()
    }


def tier_data() -> tuple[list[dict], dict[str, dict[str, str]]]:
    """The tier vocabulary in declared order, and each plugin's tier + rationale.
    A plugin named in two tiers is a declaration error, so the later one doesn't
    silently win — check-coverage reports it."""
    doc = yaml.safe_load(TIERS.read_text()) or {}
    vocab = [{"key": t["key"], "label": t["label"], "blurb": t["blurb"]} for t in doc["tiers"]]
    placed: dict[str, dict[str, str]] = {}
    for t in doc["tiers"]:
        for name, why in (t.get("plugins") or {}).items():
            placed[name] = {"tier": t["key"], "why": why}
    return vocab, placed


def main() -> int:
    components = component_sets()
    vocab, placed = tier_data()
    plugins = {}
    for name in plugin_names():  # marketplace.json order
        spec = load_plugin(name)
        if spec is None or "suite" not in spec:
            print(f"ERROR: {name}/plugin.yml is missing or has no suite: block", file=sys.stderr)
            return 1
        entry = spec["suite"]
        if "version" in spec:
            entry["version"] = str(spec["version"])
        if name in components:
            entry["components"] = components[name]
        entry.update(placed.get(name, {}))
        plugins[name] = entry

    body = json.dumps(plugins, indent=2, ensure_ascii=False)
    tiers = json.dumps(vocab, indent=2, ensure_ascii=False)
    TARGET.write_text(
        "// Generated by suite/build-plugins-data.py — do not edit by hand.\n"
        "// Per-plugin content comes from each plugin's plugin.yml (suite: block);\n"
        "// the adoption tiers come from suite/tiers.yml.\n"
        f"const TIERS = {tiers};\n"
        f"const PLUGINS = {body};\n"
    )
    print(f"wrote {TARGET.relative_to(ROOT)} — {len(plugins)} plugins from plugin.yml, "
          f"{len(vocab)} tiers from tiers.yml")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
