#!/usr/bin/env python3
"""Generate docs/plugins.js — the SPA's PLUGINS data — from each plugin's
plugin.yml (the `suite:` block), falling back to suite/spa-legacy.json for
plugins that haven't migrated yet. spa-legacy.json (a verbatim snapshot of the
original inline PLUGINS object) supplies both the display order and the content
for not-yet-migrated plugins. docs/plugins.js is ephemeral — regenerated each
deploy, not committed.
"""
import json
import pathlib
import sys

from _common import ROOT, load_plugin

LEGACY = ROOT / "suite" / "spa-legacy.json"
TARGET = ROOT / "docs" / "plugins.js"


def main() -> int:
    legacy = json.loads(LEGACY.read_text())
    plugins = {}
    migrated = []
    for name in legacy:  # legacy key order is the display order
        spec = load_plugin(name)
        if spec is not None and "suite" in spec:
            plugins[name] = spec["suite"]
            migrated.append(name)
        else:
            if spec is not None:
                print(f"WARNING: {name}/plugin.yml has no suite: block — using legacy entry", file=sys.stderr)
            plugins[name] = legacy[name]

    body = json.dumps(plugins, indent=2, ensure_ascii=False)
    TARGET.write_text(
        "// Generated by suite/build-spa-data.py — do not edit by hand.\n"
        "// Per-plugin content comes from each plugin's plugin.yml (suite: block);\n"
        "// not-yet-migrated plugins fall back to suite/spa-legacy.json.\n"
        f"const PLUGINS = {body};\n"
    )
    print(f"wrote {TARGET.relative_to(ROOT)} — from plugin.yml: {', '.join(migrated) or '(none yet)'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
